Update jenkinsfile_Manual_Version_deploy

diff --git a/Jenkins/jenkinsfile_Manual_Version_deploy b/Jenkins/jenkinsfile_Manual_Version_deploy
--- a/Jenkins/jenkinsfile_Manual_Version_deploy
+++ b/Jenkins/jenkinsfile_Manual_Version_deploy
@@ -30,13 +30,19 @@ pipeline {
         stage('Check Docker Image') {
             steps {
                 script {
-                    def imageExists = checkDockerImageExists($dockerRepo, $appVersion)
-
-                    if (imageExists) {
-                        echo "Docker image ${dockerRepo}:${appVersion} exists in the repository."
-                    } else {
-                        error("Docker image ${dockerRepo}:${appVersion} does not exist in the repository.")
-                        exit 1
+                    echo '<--------------- Checking Docker Image --------------->'
+                    echo "${dockerRepo}:v${appVersion}"
+                    try {
+                        sh '''
+                            if ! docker pull ${dockerRepo}:v${appVersion} >/dev/null 2>&1; then
+                                echo "Docker image ${dockerRepo}:v${appVersion} does not exist."
+                                exit 1
+                            fi
+                        '''
+                    } catch (Exception e) {
+                        echo "Error checking Docker image: ${e.message}"
+                        currentBuild.result = 'FAILURE'
+                        error("Docker image ${dockerRepo}:v${appVersion} does not exist.")
                     }
                 }
             }
