Update jenkinsfile_Manual_Version_deploy

diff --git a/Jenkins/jenkinsfile_Manual_Version_deploy b/Jenkins/jenkinsfile_Manual_Version_deploy
--- a/Jenkins/jenkinsfile_Manual_Version_deploy
+++ b/Jenkins/jenkinsfile_Manual_Version_deploy
@@ -27,6 +27,29 @@ pipeline {
             }
         }
 
+        stage('Check Docker Image ') {
+            steps {
+                script {
+                    echo '<--------------- Checking Docker Image --------------->'
+                    echo "${dockerRepo}:v${appVersion}"
+                    try {
+                       ssh '''
+                        if ! docker images -q ${dockerRepo}:v${appVersion} >/dev/null 2>&1; then
+                            echo "Docker image ${dockerRepo}:v${appVersion} does not exist."
+                            exit 1
+                        else
+                            echo "Docker image ${dockerRepo}:v${appVersion} exists."
+                        fi
+                        '''
+                    } catch (Exception e) {
+                        echo "Error checking Docker image: ${e.message}"
+                        currentBuild.result = 'FAILURE'
+                        error("Docker image ${dockerRepo}:v${appVersion} does not exist.")
+                    }
+                }
+            }
+        }
+
         stage('Create Helm Chart') {
             steps {
                 sh'''
